# Incase bukkit is trying to use Roku as a plugin.
main: com.ankoki.roku.bukkit.BukkitImpl
name: Roku
version: 1.0-dev
api-version: 1.13
author: Ankoki
commands:
  roku:
    description: debug command.