# Incase bukkit is trying to use Roku as a plugin; which is plausible.
main: com.ankoki.roku.bukkit.BukkitImpl
name: Roku
version: @VERSION@
api-version: 1.13
author: Ankoki
commands:
  roku:
    description: debug command.